<?php

namespace App\Http\Requests\Admin;

use App\Enums\ProductType;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ProductRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        $productId = $this->route('product')?->id;

        return [
            'save_mode' => ['nullable', Rule::in(['draft', 'publish'])],
            'category_id' => ['required', 'exists:categories,id'],
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['nullable', 'string', 'max:255', Rule::unique('products', 'slug')->ignore($productId)],
            'sku' => ['nullable', 'string', 'max:255', Rule::unique('products', 'sku')->ignore($productId)],
            'type' => ['required', Rule::enum(ProductType::class)],
            'status' => ['required', 'string', 'max:50'],
            'excerpt' => ['nullable', 'string', 'max:500'],
            'description' => ['nullable', 'string'],
            'price' => ['required', 'numeric', 'min:0'],
            'compare_at_price' => ['nullable', 'numeric', 'gte:price'],
            'lead_time_days' => ['nullable', 'integer', 'min:0'],
            'manage_stock' => ['nullable', 'boolean'],
            'stock_quantity' => ['nullable', 'integer', 'min:0'],
            'low_stock_threshold' => ['nullable', 'integer', 'min:0'],
            'is_featured' => ['nullable', 'boolean'],
            'featured_image_upload' => ['nullable', 'image', 'max:5120'],
            'video_url' => ['nullable', 'url', 'max:2048'],
            'proof_notes_enabled' => ['nullable', 'boolean'],
            'font_presets_enabled' => ['nullable', 'boolean'],
            'assigned_template_id' => ['nullable', 'exists:personalization_templates,id'],
            'allowed_mockup_ids' => ['nullable', 'array'],
            'allowed_mockup_ids.*' => ['integer', 'exists:personalization_mockups,id'],
            'default_mockup_id' => ['nullable', 'integer', 'exists:personalization_mockups,id'],
            'gallery_default_source' => ['nullable', Rule::in(['template_flat_preview', 'selected_mockup', 'manual_featured_image'])],
            'show_flat_preview_first' => ['nullable', 'boolean'],
            'include_mockup_gallery' => ['nullable', 'boolean'],
            'live_preview_enabled' => ['nullable', 'boolean'],
            'personalization_help_text' => ['nullable', 'string'],
            'personalization_fields_blueprint' => ['nullable', 'json'],
            'variant_media_links' => ['nullable', 'json'],
            'shipping_care_policy' => ['nullable', 'json'],
            'product_faqs' => ['nullable', 'json'],
            'combo_discount_type' => ['nullable', Rule::in(['percent', 'fixed'])],
            'combo_discount_value' => ['nullable', 'numeric', 'min:0'],
            'combo_rounding_rule' => ['nullable', Rule::in(['none', 'nearest_10', 'nearest_50', 'nearest_100'])],
            'show_combo_savings_badge' => ['nullable', 'boolean'],
            'combo_promo_headline' => ['nullable', 'string', 'max:255'],
            'combo_promo_subtitle' => ['nullable', 'string'],
            'marketing_label' => ['nullable', 'string', 'max:255'],
            'show_related_combos_on_product' => ['nullable', 'boolean'],
            'show_related_combos_in_cart' => ['nullable', 'boolean'],
            'meta_title' => ['nullable', 'string', 'max:255'],
            'meta_description' => ['nullable', 'string', 'max:500'],
            'gallery_uploads' => ['nullable', 'array'],
            'gallery_uploads.*' => ['image', 'max:5120'],
            'existing_images' => ['nullable', 'array'],
            'existing_images.*.label' => ['nullable', 'string', 'max:100'],
            'existing_images.*.alt_text' => ['nullable', 'string', 'max:255'],
            'existing_images.*.position' => ['nullable', 'integer', 'min:0'],
            'existing_images.*.is_primary' => ['nullable', 'boolean'],
            'existing_images.*.remove' => ['nullable', 'boolean'],
            'collection_ids' => ['nullable', 'array'],
            'collection_ids.*' => ['integer', 'exists:collections,id'],
            'tag_ids' => ['nullable', 'array'],
            'tag_ids.*' => ['integer', 'exists:tags,id'],
            'related_product_ids' => ['nullable', 'array'],
            'related_product_ids.*' => ['integer', 'exists:products,id'],
            'related_category_ids' => ['nullable', 'array'],
            'related_category_ids.*' => ['integer', 'exists:categories,id'],
            'variants' => ['nullable', 'array'],
            'variants.*.name' => ['nullable', 'string', 'max:255'],
            'variants.*.sku' => ['nullable', 'string', 'max:255'],
            'variants.*.option_values' => ['nullable', 'string', 'max:255'],
            'variants.*.price' => ['nullable', 'numeric', 'min:0'],
            'variants.*.compare_at_price' => ['nullable', 'numeric', 'min:0'],
            'variants.*.stock_quantity' => ['nullable', 'integer', 'min:0'],
            'variants.*.is_default' => ['nullable', 'boolean'],
            'bundle_items' => ['nullable', 'array'],
            'bundle_items.*.child_product_id' => ['nullable', 'integer', 'exists:products,id'],
            'bundle_items.*.quantity' => ['nullable', 'integer', 'min:1'],
            'bundle_items.*.is_required' => ['nullable', 'boolean'],
            'bundle_items.*.default_variant_id' => ['nullable', 'integer', 'exists:product_variants,id'],
            'bundle_items.*.allowed_variant_ids' => ['nullable', 'array'],
            'bundle_items.*.allowed_variant_ids.*' => ['integer', 'exists:product_variants,id'],
            'bundle_items.*.variant_change_allowed' => ['nullable', 'boolean'],
            'bundle_items.*.discount_eligible' => ['nullable', 'boolean'],
            'bundle_items.*.excluded_upgrade' => ['nullable', 'boolean'],
            'bundle_items.*.price_mode' => ['nullable', Rule::in(['included_in_combo_price', 'add_child_price', 'custom_combo_price', 'upgrade_price_only'])],
            'bundle_items.*.custom_price' => ['nullable', 'numeric', 'min:0'],
            'bundle_items.*.display_label' => ['nullable', 'string', 'max:255'],
            'bundle_items.*.show_on_hero' => ['nullable', 'boolean'],
            'bundle_items.*.show_in_details' => ['nullable', 'boolean'],
            'service_meta.service_type' => ['nullable', 'string', 'max:255'],
            'service_meta.duration_label' => ['nullable', 'string', 'max:255'],
            'service_meta.location_scope' => ['nullable', 'string', 'max:255'],
            'service_meta.requires_advance_payment' => ['nullable', 'boolean'],
            'service_meta.advance_payment_amount' => ['nullable', 'numeric', 'min:0'],
            'service_meta.booking_notes' => ['nullable', 'string'],
            'service_meta.confirmation_note' => ['nullable', 'string'],
            'service_meta.available_areas' => ['nullable', 'string'],
            'service_meta.available_days' => ['nullable', 'string'],
            'service_meta.time_slot_options' => ['nullable', 'string'],
            'service_meta.minimum_notice_days' => ['nullable', 'integer', 'min:0'],
            'service_meta.max_bookings_per_day' => ['nullable', 'integer', 'min:0'],
            'service_meta.travel_outside_area_allowed' => ['nullable', 'boolean'],
            'service_meta.extra_charge_note' => ['nullable', 'string'],
            'service_meta.include_items' => ['nullable', 'json'],
            'service_meta.packages' => ['nullable', 'json'],
            'service_meta.booking_flow' => ['nullable', 'json'],
            'service_meta.before_appointment' => ['nullable', 'json'],
            'service_meta.pricing_notes' => ['nullable', 'json'],
            'service_meta.policies' => ['nullable', 'json'],
            'service_meta.faqs' => ['nullable', 'json'],
            'service_meta.gallery_intro_text' => ['nullable', 'string'],
        ];
    }
}
